//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v13.11.0+c177c30
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	// Mixin Content Type with alias "settings"
	/// <summary>Settings</summary>
	public partial interface ISettings : IPublishedElement
	{
		/// <summary>Booking Flight Link</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.11.0+c177c30")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BookingFlightLink { get; }

		/// <summary>Booking Link</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.11.0+c177c30")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BookingLink { get; }

		/// <summary>Contact Details</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.11.0+c177c30")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ContactDetails { get; }

		/// <summary>Email</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.11.0+c177c30")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ContactEmail { get; }

		/// <summary>Contact Telephone</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.11.0+c177c30")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ContactTelephone { get; }

		/// <summary>Footer Logos Picker</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.11.0+c177c30")]
		decimal FooterLogos { get; }

		/// <summary>Header Menu</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.11.0+c177c30")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HeaderMenu { get; }

		/// <summary>Logo</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.11.0+c177c30")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.Models.MediaWithCrops SiteLogo { get; }

		/// <summary>Site Name</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.11.0+c177c30")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string SiteName { get; }

		/// <summary>Social Media</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.11.0+c177c30")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string SocialMedia { get; }
	}

	/// <summary>Settings</summary>
	[PublishedModel("settings")]
	public partial class Settings : PublishedElementModel, ISettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.11.0+c177c30")]
		public new const string ModelTypeAlias = "settings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.11.0+c177c30")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.11.0+c177c30")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.11.0+c177c30")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<Settings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public Settings(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Booking Flight Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.11.0+c177c30")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("bookingFlightLink")]
		public virtual string BookingFlightLink => GetBookingFlightLink(this, _publishedValueFallback);

		/// <summary>Static getter for Booking Flight Link</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.11.0+c177c30")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBookingFlightLink(ISettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "bookingFlightLink");

		///<summary>
		/// Booking Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.11.0+c177c30")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("bookingLink")]
		public virtual string BookingLink => GetBookingLink(this, _publishedValueFallback);

		/// <summary>Static getter for Booking Link</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.11.0+c177c30")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBookingLink(ISettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "bookingLink");

		///<summary>
		/// Contact Details
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.11.0+c177c30")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactDetails")]
		public virtual string ContactDetails => GetContactDetails(this, _publishedValueFallback);

		/// <summary>Static getter for Contact Details</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.11.0+c177c30")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetContactDetails(ISettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "contactDetails");

		///<summary>
		/// Email: header icon
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.11.0+c177c30")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactEmail")]
		public virtual string ContactEmail => GetContactEmail(this, _publishedValueFallback);

		/// <summary>Static getter for Email</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.11.0+c177c30")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetContactEmail(ISettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "contactEmail");

		///<summary>
		/// Contact Telephone: header icon
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.11.0+c177c30")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactTelephone")]
		public virtual string ContactTelephone => GetContactTelephone(this, _publishedValueFallback);

		/// <summary>Static getter for Contact Telephone</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.11.0+c177c30")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetContactTelephone(ISettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "contactTelephone");

		///<summary>
		/// Footer Logos Picker: footer
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.11.0+c177c30")]
		[ImplementPropertyType("footerLogos")]
		public virtual decimal FooterLogos => GetFooterLogos(this, _publishedValueFallback);

		/// <summary>Static getter for Footer Logos Picker</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.11.0+c177c30")]
		public static decimal GetFooterLogos(ISettings that, IPublishedValueFallback publishedValueFallback) => that.Value<decimal>(publishedValueFallback, "footerLogos");

		///<summary>
		/// Header Menu
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.11.0+c177c30")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("headerMenu")]
		public virtual string HeaderMenu => GetHeaderMenu(this, _publishedValueFallback);

		/// <summary>Static getter for Header Menu</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.11.0+c177c30")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHeaderMenu(ISettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "headerMenu");

		///<summary>
		/// Logo
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.11.0+c177c30")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("siteLogo")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops SiteLogo => GetSiteLogo(this, _publishedValueFallback);

		/// <summary>Static getter for Logo</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.11.0+c177c30")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.Models.MediaWithCrops GetSiteLogo(ISettings that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(publishedValueFallback, "siteLogo");

		///<summary>
		/// Site Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.11.0+c177c30")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("siteName")]
		public virtual string SiteName => GetSiteName(this, _publishedValueFallback);

		/// <summary>Static getter for Site Name</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.11.0+c177c30")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetSiteName(ISettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "siteName");

		///<summary>
		/// Social Media
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.11.0+c177c30")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("socialMedia")]
		public virtual string SocialMedia => GetSocialMedia(this, _publishedValueFallback);

		/// <summary>Static getter for Social Media</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.11.0+c177c30")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetSocialMedia(ISettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "socialMedia");
	}
}
